-- =============================================================================
-- SANAD | 03 — Quran text and translation editions
-- =============================================================================
-- Quran is stored as structured rows (not free-text chunks) so that:
--   * the original text shown to users is always fetched from the DB by id,
--     never generated by a model;
--   * a misquoted ayah in a question can be matched against text_normalized.
-- =============================================================================

create table public.quran_surahs (
  number                smallint primary key check (number between 1 and 114),
  name_ar               text not null,
  name_transliteration  text,
  name_en               text,
  revelation_place      text check (revelation_place in ('makkah', 'madinah')),
  ayah_count            smallint not null check (ayah_count > 0)
);

create table public.quran_ayahs (
  id                  bigint generated always as identity primary key,
  surah_number        smallint not null references public.quran_surahs (number) on delete restrict,
  ayah_number         smallint not null check (ayah_number > 0),
  global_number       smallint not null unique check (global_number between 1 and 6236),
  text_uthmani        text not null,      -- الرسم العثماني as published by the approved source
  text_simple         text,               -- optional plain (imla'i) script from the same source
  text_normalized     text generated always as (private.normalize_arabic(coalesce(text_simple, text_uthmani))) stored,
  juz                 smallint check (juz between 1 and 30),
  page                smallint check (page > 0),
  source_document_id  uuid not null references public.documents (id) on delete restrict,
  created_at          timestamptz not null default now(),
  constraint quran_ayahs_surah_ayah_key unique (surah_number, ayah_number)
);

create index quran_ayahs_document_idx   on public.quran_ayahs (source_document_id);
create index quran_ayahs_normalized_trgm on public.quran_ayahs using gin (text_normalized extensions.gin_trgm_ops);

-- Translation editions are shared by Quran and Hadith translations.
-- (id, kind) is unique so child tables can enforce the right kind with a composite FK.
create table public.translation_editions (
  id               uuid primary key default gen_random_uuid(),
  slug             text not null unique check (slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  kind             text not null check (kind in ('quran', 'hadith')),
  language         text not null references public.languages (code),
  name             text not null,
  translator       text,
  publisher        text,
  source_id        uuid not null references public.sources (id) on delete restrict,
  approval_status  public.approval_status not null default 'pending_review',
  is_default       boolean not null default false,
  notes            text,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  constraint translation_editions_id_kind_key unique (id, kind),
  constraint translation_editions_default_must_be_usable
    check (not is_default or approval_status in ('approved', 'approximate'))
);

-- At most one default edition per (kind, language).
create unique index translation_editions_one_default
  on public.translation_editions (kind, language) where is_default;

create trigger translation_editions_set_updated_at
  before update on public.translation_editions
  for each row execute function private.set_updated_at();

comment on column public.translation_editions.approval_status is
  'approved = official approved translation (e.g. King Fahd Complex); approximate = rendering of meaning that must be labelled as such in the UI.';

create table public.quran_translations (
  id            bigint generated always as identity primary key,
  ayah_id       bigint not null references public.quran_ayahs (id) on delete cascade,
  edition_id    uuid not null,
  edition_kind  text not null default 'quran' check (edition_kind = 'quran'),
  text          text not null check (length(btrim(text)) > 0),
  footnotes     text,
  created_at    timestamptz not null default now(),
  constraint quran_translations_edition_fk
    foreign key (edition_id, edition_kind)
    references public.translation_editions (id, kind) on delete restrict,
  constraint quran_translations_ayah_edition_key unique (ayah_id, edition_id)
);

create index quran_translations_edition_idx on public.quran_translations (edition_id);
